"""first db

Revision ID: 784aebc9f5b3
Revises: 96a7b20d6eff
Create Date: 2026-03-31 15:58:16.258080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784aebc9f5b3'
down_revision: Union[str, Sequence[str], None] = '96a7b20d6eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_settings_id'), ['id'], unique=False)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_id'), ['id'], unique=False)

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_id'), ['id'], unique=False)

    with op.batch_alter_table('score_buttons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_buttons_id'), ['id'], unique=False)

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_id'), ['id'], unique=False)

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songs_id'), ['id'], unique=False)

    with op.batch_alter_table('team_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_scores_id'), ['id'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    with op.batch_alter_table('team_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_scores_id'))

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songs_id'))

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_id'))

    with op.batch_alter_table('score_buttons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_buttons_id'))

    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_id'))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_id'))

    with op.batch_alter_table('admin_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_settings_id'))

    # ### end Alembic commands ###
